info:
  app:
    name: Movie Service

server:
  port: 8091

spring:
  application:
    name: movie-service
  h2:
    console:
      enabled: true
      path: /h2

springdoc:
  packages-to-scan: microservice.workshop.movieservice.http

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1.127.0.0.1.nip.io:8761/eureka/,http://eureka2.127.0.0.1.nip.io:8762/eureka/
