apiVersion: v1
kind: Service
metadata:
  labels:
    app: movie-service
  name: movie-service
spec:
  ports:
    - port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    app: movie-service
  type: ClusterIP
status:
  loadBalancer: {}
