info:
  app:
    name: Movie Aggregator Service

server:
  port: 8080

# TODO - uncomment (Exercise 5)
#feign:
#  hystrix:
#    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,hystrix.stream

# set the threshold low so we can see the circuit trip
# TODO - uncomment (Exercise 5)
#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        requestVolumeThreshold: 2
