info:
  app:
    name: Movie Aggregator Service

spring:
  application:
    name: movie-aggregator-service

server:
  port: 8080

serviceUrls:
  movieService: http://localhost:8081
  movieCastService: http://localhost:8082
  movieAwardService: http://localhost:8083

# TODO - uncomment (Exercise 5)
#feign:
#  hystrix:
#    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,hystrix.stream

# set the threshold low so we can see the circuit trip
# TODO - uncomment (Exercise 5)
#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        requestVolumeThreshold: 2
