info:
  app:
    name: Movie Aggregator Service (RT)

spring:
  application:
    name: movie-aggregator-service-rt
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
