info:
  app:
    name: Movie Aggregator Service (RT)

spring:
  application:
    name: movie-aggregator-service-rt

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

springdoc:
  packages-to-scan: microservice.workshop.movieaggregatorservicert.http
