info:
  app:
    name: Movie Cast Service

server:
  port: 8092

spring:
  application:
    name: movie-cast-service
  h2:
    console:
      enabled: true
      path: /h2

springdoc:
  packages-to-scan: microservice.workshop.moviecastservice.http
