apiVersion: v1
kind: Service
metadata:
  labels:
    app: movie-award-service
  name: movie-award-service
spec:
  ports:
    - port: 8093
      protocol: TCP
      targetPort: 8093
  selector:
    app: movie-award-service
  type: ClusterIP
status:
  loadBalancer: {}
