info:
  app:
    name: Movie Award Service

server:
  port: 8093

spring:
  application:
    name: movie-award-service
  h2:
    console:
      enabled: true
      path: /h2

springdoc:
  packages-to-scan: microservice.workshop.movieawardservice.http
